### ISSUE TITLE
new to coding and unfortunately couldnt make it work urllib2 problem

### ISSUE THREAD

**Issue by berkinimamoglu** [bwentzloff/trading-bot#12]
Hi,

I copy / pasted this code but having this error.

/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/berkinimamoglu/PycharmProjects/poloniex.py
Traceback (most recent call last):
  File "/Users/berkinimamoglu/PycharmProjects/poloniex.py", line 4, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

Process finished with exit code 1

Can you please help me?

**Comment by foglasbit** [comment]
Hello, 

I have the same Issue, did anyone find the solution? Also a noob on python.

Thanks

**Comment by bwentzloff** [comment]
You’re probably on Python 3. These scripts are for 2.7.

**Comment by sbudelman** [comment]
You're on Python 3. In order to get the code working you need either use a tool such as 2to3 (more on this here https://stackoverflow.com/questions/2792650/python3-error-import-error-no-module-name-urllib2) or change the way you import the package.

What I did was replace

`import urllib
import urllib2`

with

`from urllib.request import urlopen, Request`

Then you need to rewrite the api_query object as:

`def api_query(self, command, req={}):

        if(command == "returnTicker" or command == "return24Volume"):
            ret = urlopen(Request('https://poloniex.com/public?command=' + command))
            return json.loads(ret.read())
        elif(command == "returnOrderBook"):
            ret = urlopen(Request('https://poloniex.com/public?command=' + command + '&currencyPair=' + str(req['currencyPair'])))
            return json.loads(ret.read())
        elif(command == "returnMarketTradeHistory"):
            ret = urlopen(Request('https://poloniex.com/public?command=' + "returnTradeHistory" + '&currencyPair=' + str(req['currencyPair'])))
            return json.loads(ret.read())
        elif(command == "returnChartData"):
            ret = urlopen(Request('https://poloniex.com/public?command=returnChartData&currencyPair=' + str(req['currencyPair']) + '&start=' + str(req['start']) + '&end=' + str(req['end']) + '&period=' + str(req['period'])))
            return json.loads(ret.read())
        else:
            req['command'] = command
            req['nonce'] = int(time.time()*1000)
            post_data = urllib.urlencode(req)

            sign = hmac.new(self.Secret, post_data, hashlib.sha512).hexdigest()
            headers = {
                'Sign': sign,
                'Key': self.APIKey
            }

            ret = urllib.urlopen(urllib.Request('https://poloniex.com/tradingApi', post_data, headers))
            jsonRet = json.loads(ret.read())
            return self.post_process(jsonRet)
`

**Comment by donkhu** [comment]
import urllib
import urllib3
import json
import time
import hmac,hashlib,certifi

def createTimeStamp(datestr, format="%Y-%m-%d %H:%M:%S"):
    return time.mktime(time.strptime(datestr, format))

class poloniex:
    def __init__(self, APIKey, Secret):
        self.APIKey = APIKey
        self.Secret = Secret

    def post_process(self, before):
        after = before

        # Add timestamps if there isnt one but is a datetime
        if('return' in after):
            if(isinstance(after['return'], list)):
                for x in xrange(0, len(after['return'])):
                    if(isinstance(after['return'][x], dict)):
                        if('datetime' in after['return'][x] and 'timestamp' not in after['return'][x]):
                            after['return'][x]['timestamp'] = float(createTimeStamp(after['return'][x]['datetime']))
                            
        return after

    def api_query(self, command, req={}):

        if(command == "returnTicker" or command == "return24Volume"):
            url = 'https://poloniex.com/public?command=' + command
            http = http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
            ret = http.request('GET', url)
            #  dta = json.loads(ret.data.decode('utf-8'))

            
            return json.loads(ret.data.decode('utf-8'))#json.loads(ret.read())
        
        elif(command == "returnOrderBook"):
            url = 'https://poloniex.com/public?command=' + command + '&currencyPair=' + str(req['currencyPair'])
            http = http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
            ret = http.request('GET', url)
            return json.loads(ret.data.decode('utf-8'))
        
        
        elif(command == "returnMarketTradeHistory"):
            url = 'https://poloniex.com/public?command=' + "returnTradeHistory" + '&currencyPair=' + str(req['currencyPair'])
            http = http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
            ret = http.request('GET', url)
            return json.loads(ret.data.decode('utf-8'))

        elif(command == "returnChartData"):
            url = 'https://poloniex.com/public?command=' + "returnChartData" + '&currencyPair=' + str(req['currencyPair']) + '&start=' + str(req['start']) + '&end=' + str(req['end']) + '&period=' + str(req['period'])
            http = http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
            ret = http.request('GET', url)
            return json.loads(ret.data.decode('utf-8'))        
        
        else:
            req['command'] = command
            req['nonce'] = int(time.time()*1000)
            
            post_data = urllib.parse.urlencode(req)

            sign = hmac.new(self.Secret, post_data, hashlib.sha512).hexdigest()
            headers = {
                'Sign': sign,
                'Key': self.APIKey
            }
            url ='https://poloniex.com/tradingApi', post_data, headers
            http = http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certifi.where())
            ret = http.request('GET', url)
            jsonRet = json.loads(ret.data.decode('utf-8'))
            
            return self.post_process(jsonRet)


    def returnTicker(self):
        return self.api_query("returnTicker")

    def return24Volume(self):
        return self.api_query("return24Volume")

    def returnOrderBook (self, currencyPair):
        return self.api_query("returnOrderBook", {'currencyPair': currencyPair})

    def returnMarketTradeHistory (self, currencyPair):
        return self.api_query("returnMarketTradeHistory", {'currencyPair': currencyPair})


    # Returns all of your balances.
    # Outputs: 
    # {"BTC":"0.59098578","LTC":"3.31117268", ... }
    def returnBalances(self):
        return self.api_query('returnBalances')

    # Returns your open orders for a given market, specified by the "currencyPair" POST parameter, e.g. "BTC_XCP"
    # Inputs:
    # currencyPair  The currency pair e.g. "BTC_XCP"
    # Outputs: 
    # orderNumber   The order number
    # type          sell or buy
    # rate          Price the order is selling or buying at
    # Amount        Quantity of order
    # total         Total value of order (price * quantity)
    def returnOpenOrders(self,currencyPair):
        return self.api_query('returnOpenOrders',{"currencyPair":currencyPair})


    # Returns your trade history for a given market, specified by the "currencyPair" POST parameter
    # Inputs:
    # currencyPair  The currency pair e.g. "BTC_XCP"
    # Outputs: 
    # date          Date in the form: "2014-02-19 03:44:59"
    # rate          Price the order is selling or buying at
    # amount        Quantity of order
    # total         Total value of order (price * quantity)
    # type          sell or buy
    def returnTradeHistory(self,currencyPair):
        return self.api_query('returnTradeHistory',{"currencyPair":currencyPair})

    # Places a buy order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". If successful, the method will return the order number.
    # Inputs:
    # currencyPair  The curreny pair
    # rate          price the order is buying at
    # amount        Amount of coins to buy
    # Outputs: 
    # orderNumber   The order number
    def buy(self,currencyPair,rate,amount):
        return self.api_query('buy',{"currencyPair":currencyPair,"rate":rate,"amount":amount})

    # Places a sell order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". If successful, the method will return the order number.
    # Inputs:
    # currencyPair  The curreny pair
    # rate          price the order is selling at
    # amount        Amount of coins to sell
    # Outputs: 
    # orderNumber   The order number
    def sell(self,currencyPair,rate,amount):
        return self.api_query('sell',{"currencyPair":currencyPair,"rate":rate,"amount":amount})

    # Cancels an order you have placed in a given market. Required POST parameters are "currencyPair" and "orderNumber".
    # Inputs:
    # currencyPair  The curreny pair
    # orderNumber   The order number to cancel
    # Outputs: 
    # succes        1 or 0
    def cancel(self,currencyPair,orderNumber):
        return self.api_query('cancelOrder',{"currencyPair":currencyPair,"orderNumber":orderNumber})

    # Immediately places a withdrawal for a given currency, with no email confirmation. In order to use this method, the withdrawal privilege must be enabled for your API key. Required POST parameters are "currency", "amount", and "address". Sample output: {"response":"Withdrew 2398 NXT."} 
    # Inputs:
    # currency      The currency to withdraw
    # amount        The amount of this coin to withdraw
    # address       The withdrawal address
    # Outputs: 
    # response      Text containing message about the withdrawal
    def withdraw(self, currency, amount, address):
        return self.api_query('withdraw',{"currency":currency, "amount":amount, "address":address})

**Comment by berkinimamoglu** [comment]
@sbudelman 

i typed python to terminal window and got this.
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> license


so , 2.7.13 is installed .i m using pycharm btw.  the last thing that came into my mind is , i might use the wrong project interpreter. i will change it into same as 2.7.13. i will let you know if this bot works.

**Comment by sbudelman** [comment]
Jmmm okok.. Post if you need further help

**Comment by foglasbit** [comment]
Thanks for the information I'll give it a try.

**Comment by Dross61** [comment]
Hi, I don't think I'm prep'ing my api and secret correctly before calling api_query.  Any help appreciated.
Using Python 3.6  Thanks.

api_key=bytearray("P***lots removed***E".encode('utf-8'))
api_secret=bytearray("f***lots removed***0".encode('utf-8'))

TypeError: Unicode-objects must be encoded before hashing

  File "C:\Users\bobc\AppData\Roaming\SPB_16.6\.spyder-py3\poloniexapi.py", line 110, in returnBalances
    return self.api_query('returnBalances')

  File "C:\Users\bobc\AppData\Roaming\SPB_16.6\.spyder-py3\poloniexapi.py", line 81, in api_query
    sign = hmac.new(self.Secret, post_data, hashlib.sha512).hexdigest()

  File "C:\ProgramData\Anaconda3\lib\hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)

  File "C:\ProgramData\Anaconda3\lib\hmac.py", line 84, in __init__
    self.update(msg)

  File "C:\ProgramData\Anaconda3\lib\hmac.py", line 93, in update
    self.inner.update(msg)

TypeError: Unicode-objects must be encoded before hashing

**Comment by karanratti** [comment]
@donkhu Thanks for your input. It worked for me

**Comment by igorsouda** [comment]
# How to make poloniex.py wrapper work in Python 3

**In the poloniex.py file:**

**Step 1.** Replace entire stack of imports with this:

```
import urllib
import urllib.parse
from urllib.request import urlopen
import json
import time
import hmac,hashlib
```

**Step 2.** Replace each instance of `urllib2.urlopen(urllib2.Request` with just `urlopen` and then take care of the extra closing parens. This operation is to be performed in FIVE places in total.

**Step 3.** Replace the only instance of `urllib.urlencode(req)` with `urllib.parse.urlencode(req)` 

I run Python 3.6.4, and this solution works without a hitch on my machine.
