### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'priceAverage'

### ISSUE THREAD

**Issue by grivas97** [bwentzloff/trading-bot#23]
im sorry but im new to this but what am i missing?

Traceback (most recent call last):
  File "backtest.py", line 15, in <module>
    main(sys.argv[1:])
  File "backtest.py", line 12, in main
    strategy.tick(candlestick)
  File "/home/pi/trading-bot/part_3/botstrategy.py", line 17, in tick
    print candlestick.priceAverage
AttributeError: 'dict' object has no attribute 'priceAverage'

**Comment by TechanSolutions** [comment]
After developing the live.py a few changes were made to allow a developing candlestick.

https://github.com/bwentzloff/trading-bot/issues/19
