### ISSUE TITLE
not recognizing the poloniex.py 

### ISSUE THREAD

**Issue by phixion1** [bwentzloff/trading-bot#36]
C:\Users\Walmart>bot.py
Traceback (most recent call last):
  File "C:\Users\Walmart\bot.py", line 5, in <module>
    from botchart import BotChart
  File "C:\Users\Walmart\botchart.py", line 1, in <module>
    from poloniex import poloniex
ImportError: No module named poloniex

what am I missing here,   all scripts are in the same directory including

**Comment by phixion1** [comment]
nvm fixed it.  but now its saying "no module named numpy"

**Comment by phixion1** [comment]
Traceback (most recent call last):
  File "C:\Users\Walmart\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 2.7\Scripts\backtest.py", line 29, in <module>
    main(sys.argv[1:])
  File "C:\Users\Walmart\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 2.7\Scripts\backtest.py", line 13, in main
    chart = BotChart("poloniex","BTC_XMR",300)
  File "C:\Users\Walmart\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 2.7\Scripts\botchart.py", line 44, in __init__
    self.data.append(BotCandlestick(self.period,datum['open'],datum['close'],datum['high'],datum['low'],datum['weightedAverage']))
TypeError: __init__() takes at most 6 arguments (7 given) 


now where I'm at.

**Comment by phixion1** [comment]
hehe,  yeah I figured it out last night.  THANKS for the reply though.  I really appreciate it.   Here is where I'm @ now       

File "C:\Users\Walmart\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 2.7\Scripts\botstrategy.py", line 22, in tick
    self.currentPrice = float(candlestick.priceAverage)
AttributeError: 'tuple' object has no attribute 'priceAverage'

   the part its referring to
def tick(self,candlestick):
		self.currentPrice = float(candlestick.priceAverage)    #line 22
		self.prices.append(self.currentPrice)

		self.output.log("Price: "+str(candlestick.priceAverage)+"\tMoving Average: "+str(self.indicators.movingAverage(self.prices,15)))

		self.evaluatePositions()
		self.updateOpenTrades()
		self.showPositions()


stuck again.
