### ISSUE TITLE
Run sample program met 403 error.

### ISSUE THREAD

**Issue by archerhu77** [bwentzloff/trading-bot#7]
I try to run the program on this page, but met following error:

Traceback (most recent call last):
  File "p.py", line 102, in <module>
    main(sys.argv[1:])
  File "p.py", line 60, in main
    currentValues = conn.api_query("returnTicker")
  File "/root/poloniex.py", line 36, in api_query
    ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/public?command=' + command))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

How can I solve this problem?

**Comment by awratten** [comment]
Is it probably something to do with the API Key?

**Comment by archerhu77** [comment]
The API what downloaded from poloniex, is named poloniex.py and place in same directory.

**Comment by awratten** [comment]
in botchart.py you need to enter your API key & Secret into the following line:
`self.conn = poloniex('key goes here','key goes here')`

the format is: 
'Api Key', 'Secret'

the poloniex.py should not need to be changed at all from the original code.

let me know if you need any more information.

**Comment by archerhu77** [comment]
place my keys like following still met same error.
conn = poloniex('MyKey', 'My Secret')

if I use self.conn then met error:
NameError: global name 'self' is not defined

**Comment by awratten** [comment]
Could you please post all your code? 

The self. Is because it's inside a class. 

If everything fails you should try using the alternative Poloniex API wrapper: 
'pip install https://github.com/s4w3d0ff/python-poloniex/archive/v0.4.4.zip'

Then use:
'from poloniex import Poloniex'

**Comment by archerhu77** [comment]
the code are following:
poloniex.py

`

    #!/usr/bin/python
    # -*- coding:utf-8 -*-

    import urllib
    import urllib2
    import json
    import time
    import hmac
    import hashlib


    def createTimeStamp(datestr, format="%Y-%m-%d %H:%M:%S"):
        return time.mktime(time.strptime(datestr, format))


    class poloniex:
        def __init__(self, APIKey, Secret):
            self.APIKey = APIKey
            self.Secret = Secret

        def post_process(self, before):
            after = before

            # Add timestamps if there isnt one but is a datetime
            if('return' in after):
                if(isinstance(after['return'], list)):
                    for x in xrange(0, len(after['return'])):
                        if(isinstance(after['return'][x], dict)):
                            if('datetime' in after['return'][x] and 'timestamp' not in after['return'][x]):
                                after['return'][x]['timestamp'] = float(createTimeStamp(after['return'][x]['datetime']))
            return after

        def api_query(self, command, req={}):

            if(command == "returnTicker" or command == "return24Volume"):
                ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/public?command=' + command))
                return json.loads(ret.read())
            elif(command == "returnOrderBook"):
                ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/public?command=' + command + '&currencyPair=' + str(req['currencyPair'])))
                return json.loads(ret.read())
            elif(command == "returnMarketTradeHistory"):
                ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/public?command=' + "returnTradeHistory" + '&currencyPair=' + str(req['currencyPair'])))
                return json.loads(ret.read())
            else:
                req['command'] = command
                req['nonce'] = int(time.time() * 1000)
                post_data = urllib.urlencode(req)
                sign = hmac.new(self.Secret, post_data, hashlib.sha512).hexdigest()
                headers = {
                    'Sign': sign,
                    'Key': self.APIKey
                }
                ret = urllib2.urlopen(urllib2.Request('https://poloniex.com/tradingApi', post_data, headers))
                jsonRet = json.loads(ret.read())
                return self.post_process(jsonRet)

        def returnTicker(self):
            return self.api_query("returnTicker")

        def return24Volume(self):
            return self.api_query("return24Volume")

        def returnOrderBook(self, currencyPair):
            return self.api_query("returnOrderBook", {'currencyPair': currencyPair})

        def returnMarketTradeHistory(self, currencyPair):
            return self.api_query("returnMarketTradeHistory", {'currencyPair': currencyPair})

        # Returns all of your balances.
        # Outputs:
        # {"BTC":"0.59098578","LTC":"3.31117268", ... }
        def returnBalances(self):
            return self.api_query('returnBalances')

        # Returns your open orders for a given market, specified by the "currencyPair" POST parameter, e.g. "BTC_XCP"
        # Inputs:
        # currencyPair  The currency pair e.g. "BTC_XCP"
        # Outputs:
        # orderNumber   The order number
        # type          sell or buy
        # rate          Price the order is selling or buying at
        # Amount        Quantity of order
        # total         Total value of order (price * quantity)

        def returnOpenOrders(self, currencyPair):
            return self.api_query('returnOpenOrders', {"currencyPair": currencyPair})

        # Returns your trade history for a given market, specified by the "currencyPair" POST parameter
        # Inputs:
        # currencyPair  The currency pair e.g. "BTC_XCP"
        # Outputs:
        # date          Date in the form: "2014-02-19 03:44:59"
        # rate          Price the order is selling or buying at
        # amount        Quantity of order
        # total         Total value of order (price * quantity)
        # type          sell or buy

        def returnTradeHistory(self, currencyPair):
            return self.api_query('returnTradeHistory', {"currencyPair": currencyPair})

        # Places a buy order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". If successful, the method will return the order number.
        # Inputs:
        # currencyPair  The curreny pair
        # rate          price the order is buying at
        # amount        Amount of coins to buy
        # Outputs:
        # orderNumber   The order number

        def buy(self, currencyPair, rate, amount):
            return self.api_query('buy', {"currencyPair": currencyPair, "rate": rate, "amount": amount})

        # Places a sell order in a given market. Required POST parameters are "currencyPair", "rate", and "amount". If successful, the method will return the order number.
        # Inputs:
        # currencyPair  The curreny pair
        # rate          price the order is selling at
        # amount        Amount of coins to sell
        # Outputs:
        # orderNumber   The order number
        def sell(self, currencyPair, rate, amount):
            return self.api_query('sell', {"currencyPair": currencyPair, "rate": rate, "amount": amount})

        # Cancels an order you have placed in a given market. Required POST parameters are "currencyPair" and "orderNumber".
        # Inputs:
        # currencyPair  The curreny pair
        # orderNumber   The order number to cancel
        # Outputs:
        # succes        1 or 0

        def cancel(self, currencyPair, orderNumber):
            return self.api_query('cancelOrder', {"currencyPair": currencyPair, "orderNumber": orderNumber})

        # Immediately places a withdrawal for a given currency, with no email confirmation. In order to use this method, the withdrawal privilege must be enabled for your API key. Required POST parameters are "currency", "amount", and "address". Sample output: {"response":"Withdrew 2398 NXT."}
        # Inputs:
        # currency      The currency to withdraw
        # amount        The amount of this coin to withdraw
        # address       The withdrawal address
        # Outputs:
        # response      Text containing message about the withdrawal
        def withdraw(self, currency, amount, address):
            return self.api_query('withdraw', {"currency": currency, "amount": amount, "address": address})
        
`

trade-bot.py

`

    import time
    import sys, getopt
    import datetime
    from poloniex import poloniex

    def main(argv):
        period = 10
        pair = "BTC_XML"
        prices = []
        currentMovingAverage = 0;
        lengthOfMA = 0
        startTime = False
        endTime = False
        historicalData = False
        tradePlaced = False
        typeOfTrade = False
        dataDate = ""
        orderNumber = ""

        try:
            opts, args = getopt.getopt(argv,"hp:c:n:s:e:",["period=","currency=","points="])
        except getopt.GetoptError:
            print 'trading-bot.py -p <period length> -c <currency pair> -n <period of moving average>'
            sys.exit(2)

        for opt, arg in opts:
            if opt == '-h':
                print 'trading-bot.py -p <period length> -c <currency pair> -n <period of moving average>'
                sys.exit()
            elif opt in ("-p", "--period"):
                if (int(arg) in [300,900,1800,7200,14400,86400]):
                    period = arg
                else:
                    print 'Poloniex requires periods in 300,900,1800,7200,14400, or 86400 second increments'
                    sys.exit(2)
            elif opt in ("-c", "--currency"):
                pair = arg
            elif opt in ("-n", "--points"):
                lengthOfMA = int(arg)
            elif opt in ("-s"):
                startTime = arg
            elif opt in ("-e"):
                endTime = arg



        conn = poloniex('MyKey','MySecret')

        if (startTime):
            historicalData = conn.api_query("returnChartData",{"currencyPair":pair,"start":startTime,"end":endTime,"period":period})

        while True:
            if (startTime and historicalData):
                nextDataPoint = historicalData.pop(0)
                lastPairPrice = nextDataPoint['weightedAverage']
                dataDate = datetime.datetime.fromtimestamp(int(nextDataPoint['date'])).strftime('%Y-%m-%d %H:%M:%S')
            elif(startTime and not historicalData):
                exit()
            else:
                currentValues = conn.api_query("returnTicker")
                lastPairPrice = currentValues[pair]["last"]
                dataDate = datetime.datetime.now()

            if (len(prices) > 0):
                currentMovingAverage = sum(prices) / float(len(prices))
                previousPrice = prices[-1]
                if (not tradePlaced):
                    if ( (lastPairPrice > currentMovingAverage) and (lastPairPrice < previousPrice) ):
                        print "SELL ORDER"
                        orderNumber = conn.sell(pair,lastPairPrice,.01)
                        tradePlaced = True
                        typeOfTrade = "short"
                    elif ( (lastPairPrice < currentMovingAverage) and (lastPairPrice > previousPrice) ):
                        print "BUY ORDER"
                        orderNumber = conn.buy(pair,lastPairPrice,.01)
                        tradePlaced = True
                        typeOfTrade = "long"
                elif (typeOfTrade == "short"):
                    if ( lastPairPrice < currentMovingAverage ):
                        print "EXIT TRADE"
                        conn.cancel(pair,orderNumber)
                        tradePlaced = False
                        typeOfTrade = False
                elif (typeOfTrade == "long"):
                    if ( lastPairPrice > currentMovingAverage ):
                        print "EXIT TRADE"
                        conn.cancel(pair,orderNumber)
                        tradePlaced = False
                        typeOfTrade = False
            else:
                previousPrice = 0

            print "%s Period: %ss %s: %s Moving Average: %s" % (dataDate,period,pair,lastPairPrice,currentMovingAverage)

            prices.append(float(lastPairPrice))
            prices = prices[-lengthOfMA:]
            if (not startTime):
                time.sleep(int(period))


    if __name__ == "__main__":
        main(sys.argv[1:])
`

I had use my key and secrect, but when I run python trade-bot.py, it always met 403 error.

**Comment by awratten** [comment]
At the moment the trading bot is not implemented... Only the backtest feature is active in the latest version. 

You'll add the API key and secret into "botchart.py"

Then run backtest.py

**Comment by bwentzloff** [comment]
Ill make this more clear tomorrow and clean some things up. I'll also add a README with setup instructions. Thanks for answering these questions, Anthony.

**Comment by archerhu77** [comment]
@bwentzloff Could you write some tips(or individual code sample) that how can use poloniex python API to do individual things like: receive tick from poloniex, place an order, cancel order, receive information of trade from exchange, etc.
And do you know is there any simulation trading interface in poloniex for test?

**Comment by archerhu77** [comment]
@bwentzloff Could you?

**Comment by 1baga** [comment]
I ma having same problem. and i am running python 2.7
